schema: workflow/2022.04
name: Xero Transactions Flow
inactive: true
settings:
  concurrency: 1
  error_notification: true
  lambda_memory: 768
  lambda_timeout: 118
  max_event_queue_size: 5840
  rate_limit: 1
triggers:
- id: hi_NQHZB3V
- id: sub_7gURQ0d
steps:
- namespace: GET_invoice_Xero
  runtime: nodejs20.x
  uses: "./GET_invoice_Xero/entry.js"
  props:
    tenant_id: "{{steps.trigger.event.body.event_details.tenantId}}"
    invoice_id: "{{steps.trigger.event.body.event_details.resourceId}}"
    access_token: "{{steps.trigger.event.headers.new_xero_token}}"
- namespace: stop_condition_no_requests
  runtime: nodejs20.x
  uses: "./stop_condition_no_requests/entry.js"
- namespace: get_history_dates
  notes: |-
    Pulls Created dates both for contact and invoices.
    Manipulates data to match format. both for updated (previous step) and created.
  runtime: nodejs20.x
  uses: "./get_history_dates/entry.js"
  props:
    tenant_id: "{{steps.trigger.event.body.event_details.tenantId}}"
    access_token: "{{steps.trigger.event.headers.new_xero_token}}"
    contact_guid: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].Contact.ContactID}}"
    invoice_guid: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].InvoiceID}}"
    contact_updated_date: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].Contact.UpdatedDateUTC}}"
    invoice_updated_date: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].UpdatedDateUTC}}"
- namespace: get_token_complyt
  runtime: nodejs18.x
  uses: http-put-request@1.1.1
  props:
    httpRequest:
      auth:
        type: none
        username: ''
        password: ''
        token: ''
      body:
        contentType: application/json
        fields:
        - name: clientId
          value: "{{steps.trigger.event.headers.complyt_client_id}}"
        - name: clientSecret
          value: "{{steps.trigger.event.headers.complyt_client_secret}}"
        mode: fields
        type: fields
      headers:
      - name: ''
        value: ''
        disabled: true
      method: POST
      params:
      - name: ''
        value: ''
        disabled: true
      url: https://{{steps.trigger.event.headers.complyt_api_environment}}.complyt.io/v1/token
      tab: Body
- namespace: get_rates
  notes: Pulls the Tax rate ID's
  runtime: nodejs20.x
  uses: "./get_rates/entry.js"
- namespace: data_mapper
  runtime: nodejs20.x
  uses: "./data_mapper/entry.js"
- namespace: try_get_customer
  runtime: nodejs20.x
  uses: "./try_get_customer/entry.js"
  props:
    complyt_api_environment: "{{steps.trigger.event.headers.complyt_api_environment}}"
    contactID: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].Contact.ContactID}}"
    accessToken: "{{steps.get_token_complyt.$return_value.accessToken}}"
- namespace: put_customer
  runtime: nodejs20.x
  uses: http-put-request@1.1.1
  props:
    httpRequest:
      auth:
        type: bearer
        username: ''
        password: ''
        token: "{{steps.get_token_complyt.$return_value.accessToken}}"
      body:
        contentType: application/json
        fields:
        - name: externalId
          value: "{{steps.get_trigger_invoice.$return_value.Invoices[0].Contact.ContactID}}"
        - name: source
          value: '6'
        - name: name
          value: "{{steps.get_trigger_invoice.$return_value.Invoices[0].Contact.Name}}"
        - name: customerType
          value: RETAIL
        - name: externalTimestamps.createdDate
          value: |2-
             { "createdDate": {{steps.get_trigger_invoice.$return_value.Invoices[0].Contact.UpdatedDateUTC}},
            "updatedDate": {{steps.get_trigger_invoice.$return_value.Invoices[0].Contact.UpdatedDateUTC}} }
        - name: email
          value: "{{steps.get_trigger_invoice.$return_value.Invoices[0].Contact.EmailAddress}}"
        - name: address.state
          value: '{{steps.get_trigger_invoice["$return_value"].Invoices[0].Contact.Addresses[0].Region}}'
        - name: address.city
          value: '{{steps.get_trigger_invoice["$return_value"].Invoices[0].Contact.Addresses[0].City}}'
        - name: address.country
          value: '{{steps.get_trigger_invoice["$return_value"].Invoices[0].Contact.Addresses[0].Country}}'
        - name: address.zip
          value: '{{steps.get_trigger_invoice["$return_value"].Invoices[0].Contact.Addresses[0].PostalCode}}'
        - name: address.street
          value: '{{steps.get_trigger_invoice["$return_value"].Invoices[0].Contact.Addresses[0].AddressLine1}}'
        mode: raw
        type: raw
        raw: |-
          {
             "externalId": "{{steps.GET_invoice_Xero["$return_value"].Invoices[0].Contact.ContactID}}",
              "source": "6",
              "name": "{{steps.GET_invoice_Xero["$return_value"].Invoices[0].Contact.Name}}",
              "address": {{steps.data_mapper["$return_value"].shippingAddress}},
                 "externalTimestamps": {
                              "createdDate": "{{steps.get_history_dates["$return_value"].contactCreatedDate}}",
                              "updatedDate": "{{steps.get_history_dates["$return_value"].contactUpdatedDate}}"
                  },
                  "customerType": "{{steps.try_get_customer.$return_value.customerType}}"
          }
      headers:
      - name: ''
        value: ''
        disabled: true
      method: PUT
      params:
      - name: ''
        value: ''
        disabled: true
      url: https://{{steps.trigger.event.headers.complyt_api_environment}}.complyt.io/v1/customers/source/6/externalId/{{steps.GET_invoice_Xero.$return_value.Invoices[0].Contact.ContactID}}
      tab: Body
    includeHeaders: true
- namespace: put_transaction
  runtime: nodejs20.x
  uses: http-custom-request@1.1.1
  props:
    httpRequest:
      auth:
        type: bearer
        username: ''
        password: ''
        token: '{{steps.get_token_complyt["$return_value"].accessToken}}'
      body:
        contentType: application/json
        fields:
        - name: ''
          value: ''
          disabled: true
        mode: raw
        type: raw
        raw: "{\n    \"externalId\": \"{{steps.GET_invoice_Xero[\"$return_value\"].Invoices[0].InvoiceID}}\",\n
          \   \"source\": \"6\",\n    \"documentName\": \"{{steps.GET_invoice_Xero[\"$return_value\"].Invoices[0].InvoiceNumber}}\",\n
          \   \"items\": {{steps.data_mapper[\"$return_value\"].items_transactions}},\n
          \   \"shippingAddress\": {{steps.data_mapper[\"$return_value\"].shippingAddress}},\n
          \   \"customerId\": \"{{steps.put_customer[\"$return_value\"].complytId}}\",\n
          \   \"transactionStatus\": \"{{steps.data_mapper[\"$return_value\"].transactionStatus}}\",\n
          \   \"transactionType\": \"{{steps.data_mapper[\"$return_value\"].transactionType}}\",\n
          \   \"externalTimestamps\": {\n        \"createdDate\":  \"{{steps.GET_invoice_Xero.$return_value.Invoices[0].DateString}}\",
          \n        \"updatedDate\": \"{{steps.get_history_dates[\"$return_value\"].invoiceUpdatedDate}}\"\n
          \   },\n \"subsidiary\": \"{{steps.trigger.event.body.subsidiary}}\"\n}"
      headers:
      - name: ''
        value: ''
        disabled: true
      method: PUT
      params:
      - name: ''
        value: ''
        disabled: true
      url: https://{{steps.trigger.event.headers.complyt_api_environment}}.complyt.io/v1/transactions/source/6/externalId/{{steps.GET_invoice_Xero["$return_value"].Invoices[0].InvoiceID}}
      tab: Body
    includeHeaders: true
- namespace: get_line_items
  runtime: nodejs20.x
  uses: "./get_line_items/entry.js"
- namespace: get_credit_notes_xero
  runtime: nodejs20.x
  uses: "./get_credit_notes_xero/entry.js"
- namespace: put_credit_notes_complyt
  runtime: nodejs20.x
  uses: "./put_credit_notes_complyt/entry.js"
  props:
    url: https://{{steps.trigger.event.headers.complyt_api_environment}}.complyt.io/v1/transactions/source/6/externalId/
- namespace: stop_condition
  runtime: nodejs20.x
  uses: "./stop_condition/entry.js"
- namespace: update_invoice_xero
  runtime: nodejs20.x
  uses: "./update_invoice_xero/entry.js"
  props:
    tenant_id: "{{steps.trigger.event.body.event_details.tenantId}}"
    access_token: "{{steps.trigger.event.headers.new_xero_token}}"
    contact: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].Contact}}"
    lineItems: "{{steps.get_line_items.$return_value.lineItems}}"
    invoiceNumber: "{{steps.GET_invoice_Xero.$return_value.Invoices[0].InvoiceNumber}}"
    lineAmountType: Exclusive

